### PR TITLE
alternative multiplication

### PR DESCRIPTION
**Pull request by kolkil**
This is faster multiplication method, based on column operations. No temporary rows needed.

### CODE REVIEW

**Comment by kokke** [comment]
Hi @kolkil and thanks for the PR :) 

Let me review the changes and get back to you. Looks promising! :)

**Comment by kokke** [comment]
@kolkil I've vetted the code and it is indeed a lot aster. 
Without allocating 2x `struct bignum` on the stack it is also more frugal with regard to resources and that rocks :+1: 

However this PR changes a lot of other things, that could be viewed as irrelevant for the change: the Makefile, the asterisk-position in pointer declarations, benchmark code (add_test.c) etc., and I do not want to pull it all. 

I could copy/paste your changes in `bignum_mul_alt` and write a comment that you contributed them, but I would like to attribute the changes to you "officially".


I don't really know my way around Github, but I don't think I can pull part of a PR (correct me if I'm wrong).

**Can you make a PR that changes just the mul-method to use column-operations?**

**Comment by kolkil** [comment]
@kokke I've just created new pull request.
Sorry for mess in the older one.

**Comment by kokke** [comment]
@kolkil no problem, and thank you for a quick response.

Do you see any problem in making `bignum_mul_alt` the default multiplication function? 

If not, I think we should just that instead, since it's faster and allocates less on the stack.

**Pull request closed without merging**
